version: '3.4'

services:

  acc.services.customers:
    image: ${DOCKER_REGISTRY-}acc.services.customers
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: src/services/customers/Dockerfile
    depends_on:
    - rabbitmq
    - mongo
    restart: always
    ports:
      - '5000:80'
      #- '44338:443'

  acc.services.vehicles:
    image: ${DOCKER_REGISTRY-}acc.services.vehicles
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: src/services/vehicles/Dockerfile
    depends_on:
    - rabbitmq
    - mongo
    - acc.services.customers
    restart: always
    ports:
      - '5002:80'
      #- '44353:443'

  acc.services.tracking:
    image: ${DOCKER_REGISTRY-}acc.services.tracking
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: src/services/tracking/Dockerfile
    depends_on:
    - rabbitmq
    - mongo
    - acc.services.vehicles
    - acc.services.customers
    restart: always
    ports:
      - '5004:80'
      #- '44340:443'

  acc.gateway.api:
    image: ${DOCKER_REGISTRY-}acc.gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    depends_on:
    - rabbitmq
    - acc.services.tracking
    - acc.services.customers
    - acc.services.vehicles
    restart: always
    ports:
      - '5006:80'
      #- '44364:443'
      
  acc.ui.spa:
    image: ${DOCKER_REGISTRY-}acc.ui.spa
    build:
      context: .
      dockerfile: src/ui/spa/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - '5008:80'
      #- '44351:443'

  mongo:
    image: mongo:4
    ports:
      - '27017:27017'

  rabbitmq: # login guest:guest
   image: rabbitmq:3-management
   ports:
   - '4369:4369'
   - '5671:5671'
   - '5672:5672'
   - '25672:25672'
   - '15671:15671'
   - '15672:15672'