version: '3.4'

services:

  acc.services.customers:
    image: ${DOCKER_REGISTRY-}acc.services.customers
    build:
      context: .
      dockerfile: src/services/customers/Dockerfile
    depends_on:
    - rabbitmq
    - mongo
    restart: always
    ports:
      - '55101:80'

  acc.services.vehicles:
    image: ${DOCKER_REGISTRY-}acc.services.vehicles
    build:
      context: .
      dockerfile: src/services/vehicles/Dockerfile
    depends_on:
    - rabbitmq
    - mongo
    - acc.services.customers
    restart: always
    ports:
      - '55103:80'

  acc.services.tracking:
    image: ${DOCKER_REGISTRY-}acc.services.tracking
    build:
      context: .
      dockerfile: src/services/tracking/Dockerfile
    depends_on:
    - rabbitmq
    - mongo
    - acc.services.vehicles
    - acc.services.customers
    restart: always
    ports:
      - '55102:80'

  acc.gateway.api:
    image: ${DOCKER_REGISTRY-}acc.gateway.api
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    depends_on:
    - rabbitmq
    - acc.services.tracking
    - acc.services.customers
    - acc.services.vehicles
    restart: always
    ports:
      - '55100:80'
      
  acc.ui.spa:
    image: ${DOCKER_REGISTRY-}acc.ui.spa
    build:
      context: .
      dockerfile: src/ui/spa/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '55104:80'

  mongo:
    image: mongo:4
    ports:
      - '27017:27017'

  rabbitmq: # login guest:guest
   image: rabbitmq:3-management
   ports:
   - '4369:4369'
   - '5671:5671'
   - '5672:5672'
   - '25672:25672'
   - '15671:15671'
   - '15672:15672'